package com.hr.assignments;

import com.hr.assignments.Person;
import com.hr.assignments.Assignment;

dialect  "mvel"

rule "Назначить курс 0001"
    when
        $person : Person( grade > 10 );
    then
        //Assignment assign = new Assignment();
        //assign.setText(person.toString());
        //insertLogical(assign)
        insertLogical(new Assignment($person))
        System.out.println("Курс 0001 назначен сотруднику " + $person);
end

query "get-assignments"
    $assignment :  Assignment()
end

query "get-persons"
    $person : Person()
end